sudo git clone https://github.com/abseil/abseil-cpp
sudo git clone https://github.com/alanxz/SimpleAmqpClient
sudo git clone https://github.com/Alinshans/MyTinySTL
sudo git clone https://github.com/amhndu/SimpleNES
sudo git clone https://github.com/Andersbakken/rtags
sudo git clone https://github.com/arvidn/libtorrent
sudo git clone https://github.com/aws/aws-sdk-cpp
sudo git clone https://github.com/catchorg/Catch2
sudo git clone https://github.com/changkun/modern-cpp-tutorial
sudo git clone https://github.com/chriskohlhoff/asio
sudo git clone https://github.com/cnjinhao/nana
sudo git clone https://github.com/cpp-taskflow/cpp-taskflow
sudo git clone https://github.com/cpputest/cpputest
sudo git clone https://github.com/csmith-project/creduce
sudo git clone https://github.com/danmar/cppcheck
sudo git clone https://github.com/Dashark/hello-world
sudo git clone https://github.com/datastax/cpp-driver
sudo git clone https://github.com/dougbinks/enkiTS
sudo git clone https://github.com/DragonBones/DragonBonesCPP
sudo git clone https://github.com/enewhuis/liquibook
sudo git clone https://github.com/eranif/codelite
sudo git clone https://github.com/ericniebler/range-v3
sudo git clone https://github.com/ethereum/aleth
sudo git clone https://github.com/facebook/folly
sudo git clone https://github.com/fengbingchun/Messy_Test
sudo git clone https://github.com/gabime/spdlog
sudo git clone https://github.com/glassechidna/zxing-cpp
sudo git clone https://github.com/google/glog
sudo git clone https://github.com/google/orbit
sudo git clone https://github.com/google/sandboxed-api
sudo git clone https://github.com/graphql/libgraphqlparser
sudo git clone https://github.com/grpc/grpc
sudo git clone https://github.com/gwaldron/osgearth
sudo git clone https://github.com/gzwl/leetcode
sudo git clone https://github.com/HandsOnOpenCL/Exercises-Solutions
sudo git clone https://github.com/JakubVojvoda/design-patterns-cpp
sudo git clone https://github.com/jbeder/yaml-cpp
sudo git clone https://github.com/jdeng/word2vec
sudo git clone https://github.com/joaofaro/KCFcpp
sudo git clone https://github.com/jpbarrette/curlpp
sudo git clone https://github.com/juce-framework/JUCE
sudo git clone https://github.com/justinhj/astar-algorithm-cpp
sudo git clone https://github.com/KhronosGroup/Vulkan-Hpp
sudo git clone https://github.com/lballabio/QuantLib
sudo git clone https://github.com/libigl/libigl
sudo git clone https://github.com/linyacool/WebServer
sudo git clone https://github.com/lvandeve/lodepng
sudo git clone https://github.com/mandliya/algorithms_and_data_structures
sudo git clone https://github.com/mapbox/variant
sudo git clone https://github.com/meganz/sdk
sudo git clone https://github.com/miao1007/Openwrt-NetKeeper
sudo git clone https://github.com/microsoft/cpprestsdk
sudo git clone https://github.com/mlpack/mlpack
sudo git clone https://github.com/mongodb/mongo-cxx-driver
sudo git clone https://github.com/Mooophy/Cpp-Primer
sudo git clone https://github.com/mortennobel/cpp-cheatsheet
sudo git clone https://github.com/mosra/corrade
sudo git clone https://github.com/mosra/magnum
sudo git clone https://github.com/msgpack/msgpack-c
sudo git clone https://github.com/nghttp2/nghttp2
sudo git clone https://github.com/nlohmann/json
sudo git clone https://github.com/oclint/oclint
sudo git clone https://github.com/open-source-parsers/jsoncpp
sudo git clone https://github.com/pezy/CppPrimer
sudo git clone https://github.com/progschj/ThreadPool
sudo git clone https://github.com/Project-OSRM/osrm-backend
sudo git clone https://github.com/protobuf-c/protobuf-c
sudo git clone https://github.com/pybind/pybind11
sudo git clone https://github.com/quarnster/SublimeClang
sudo git clone https://github.com/quickfix/quickfix
sudo git clone https://github.com/ReactiveX/RxCpp
sudo git clone https://github.com/ripple/rippled
sudo git clone https://github.com/ROCm-Developer-Tools/HIP
sudo git clone https://github.com/root-project/cling
sudo git clone https://github.com/rprichard/sourceweb
sudo git clone https://github.com/rttrorg/rttr
sudo git clone https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus
sudo git clone https://github.com/rust-lang/rust-bindgen
sudo git clone https://github.com/sass/libsass
sudo git clone https://github.com/schlangster/cpp.react
sudo git clone https://github.com/scipr-lab/libsnark
sudo git clone https://github.com/socketio/socket.io-client-cpp
sudo git clone https://github.com/sparsehash/sparsehash
sudo git clone https://github.com/sumeetchhetri/ffead-cpp
sudo git clone https://github.com/SVF-tools/SVF
sudo git clone https://github.com/tencent-wechat/libco
sudo git clone https://github.com/Tencent/phxrpc
sudo git clone https://github.com/Tencent/TscanCode
sudo git clone https://github.com/TheAlgorithms/C-Plus-Plus
sudo git clone https://github.com/thrust/thrust
sudo git clone https://github.com/tiny-dnn/tiny-dnn
sudo git clone https://github.com/trailofbits/pe-parse
sudo git clone https://github.com/USCiLab/cereal
sudo git clone https://github.com/weidai11/cryptopp
sudo git clone https://github.com/xtaci/algorithms
sudo git clone https://github.com/yyzybb537/libgo
sudo git clone https://github.com/zaphoyd/websocketpp
sudo git clone https://github.com/zeroc-ice/ice
sudo git clone https://github.com/zeromq/cppzmq
sudo git clone https://github.com/zeromq/libzmq