git clone https://github.com/abishekaditya/DesignPatterns
git clone https://github.com/BluestormDNA/ProjectPSX
git clone https://github.com/yusufshakeel/CSharp-Project
git clone https://github.com/sjdirect/abot
git clone https://github.com/aalhour/C-Sharp-Algorithms
git clone https://github.com/pluralsight-projects/CSharp-GradeBookApplication
git clone https://github.com/lightszero/cslightcore
git clone https://github.com/rogeralsing/ProjectExodus
git clone https://github.com/nikhilk/scriptsharp
git clone https://github.com/dotnet/project-system-tools
git clone https://github.com/SonarSource/sonar-dotnet
git clone https://github.com/chraft/c-raft
git clone https://github.com/PolarisTeam/PolarisServer
git clone https://github.com/BluestormDNA/ProjectDMG
git clone https://github.com/leoloobeek/csharp
git clone https://github.com/ubisoftinc/Sharpmake
git clone https://github.com/A2andil/Projects
git clone https://github.com/Gr8z/ChatBotProject
git clone https://github.com/cleavetv/unity-framework
git clone https://github.com/BloodHoundAD/SharpHound3
git clone https://github.com/amirjalilifard/FreeFilesProject
git clone https://github.com/IntelliTect/EssentialCSharp
git clone https://github.com/head-first-csharp/third-edition
git clone https://github.com/hiramtan/HiSocket
git clone https://github.com/jrusbatch/compilify
git clone https://github.com/rayosu/UnityDllInjector
git clone https://github.com/Phong13/BulletSharpUnity3d
git clone https://github.com/verybadcat/CSharpMath
git clone https://github.com/wojciech-kulik/Sample-Projects
git clone https://github.com/5argon/protobuf-unity
git clone https://github.com/dotnetcore/FlubuCore
git clone https://github.com/MarkPThomas/HeadFirst-OOAD
git clone https://github.com/heldersepu/csharp-proj
git clone https://github.com/noxad/windows-toast-notifications
git clone https://github.com/n-yoda/unity-midi
git clone https://github.com/n-yoda/unity-midi
git clone https://github.com/o2platform/O2.Platform.Projects
git clone https://github.com/GhostPack/Seatbelt
git clone https://github.com/yoonhwang/c-sharp-machine-learning
git clone https://github.com/OmerMor/AsyncBridge
git clone https://github.com/CompleteUnityDeveloper2/3_Project_Boost
git clone https://github.com/abishekaditya/DSA
git clone https://github.com/Zesix/Impulse
git clone https://github.com/CreateBrowser/SharpBrowser
git clone https://github.com/Q42/Q42.WinRT
git clone https://github.com/hieunc229/Simple-.NET-MVC-5-Shopping-Cart
git clone https://github.com/JoshVarty/ProjectionBufferTutorial
git clone https://github.com/Adam198590/GameProject
git clone https://github.com/perl-easj/Unsolved-csharp-projects
git clone https://github.com/onurhancelik/Hospital-Management-System
git clone https://github.com/vladislav-karamfilov/CSharp-Playground
git clone https://github.com/stampsy/hockeyapp-monotouch
git clone https://github.com/Dukotech/Project-Euler-Solutions
git clone https://github.com/markfinal/BuildAMation
git clone https://github.com/iricwang/ILRuntime_Protobuf
git clone https://github.com/ManarEzzadeen/ZeroMQ
git clone https://github.com/smokindinesh/Csharp-windows-form-sample
git clone https://github.com/nbarbettini/csharp-travis-example
git clone https://github.com/NewEraCracker/LOIC
git clone https://github.com/pharan/Unity-MeshSaver
git clone https://github.com/Amine-Smahi/C-Sharp-Learning-Journey
git clone https://github.com/PragmaticIT/xiconify
git clone https://github.com/PacktPublishing/C-8-and-.NET-Core-3-Projects-Using-Azure-Second-Edition
git clone https://github.com/dotnetcore/WebApiClient
git clone https://github.com/winnster/DotRas
git clone https://github.com/getgauge-examples/gauge-example-csharp
git clone https://github.com/royosherove/dotnet-perfplus
git clone https://github.com/sschmid/EntitasPure
git clone https://github.com/trashvin/Tutorial_UsingStateless
git clone https://github.com/CypherCore/CypherCore
git clone https://github.com/cs-util-com/cscore
git clone https://github.com/lxconan/clrViaTest
git clone https://github.com/zeros-team/Projects
git clone https://github.com/LaunchCodeLiftoffProjects/Late_Night_Snacks
git clone https://github.com/anton-bot/Full-Emoji-List
git clone https://github.com/pandaedward/refaction
git clone https://github.com/kwwwvagaa/NetWinformControl
git clone https://github.com/curiosity-inc/azure-kinect-dk-unity
git clone https://github.com/A9T9/Free-OCR-API-CSharp
git clone https://github.com/mbdavid/FileDB
git clone https://github.com/Patagames/Pdf.WinForms
git clone https://github.com/spatialos/CsharpBlankProject
git clone https://github.com/JackWangCUMT/NetGanttControl
git clone https://github.com/OpenEpl/EProjectFile
git clone https://github.com/JesseKPhillips/CsharpActiveX
git clone https://github.com/SohaibAjmal/DataMining-Project-CSharp
git clone https://github.com/ishani/ClangVSx
git clone https://github.com/iQuarc/Geco
git clone https://github.com/sarn1/example-aspnet-mvc
git clone https://github.com/OlgaRacu/TeamProject-POS-PointOfSales
git clone https://github.com/zyrif/Project-JobBoard
git clone https://github.com/sjdirect/abotx
git clone https://github.com/ArturT/Game-of-Life
git clone https://github.com/Hitman666/nbCcTalkCoinAcceptor
git clone https://github.com/Equipple/vs-templates-revit-addin
git clone https://github.com/olegil/SqlBulkTools
git clone https://github.com/Travelport/travelport-uapi-tutorial-c-sharp
git clone https://github.com/MarkPThomas/HeadFirst-CSharp
git clone https://github.com/uow-dmurrell/ProjectorControl
git clone https://github.com/TanvirArjel/CustomValidation