sudo git clone https://github.com/a-schild/jave2
sudo git clone https://github.com/AdamBien/javaee7-essentials-archetype
sudo git clone https://github.com/AdamBien/javaee8-essentials-archetype
sudo git clone https://github.com/apssouza22/java-microservice
sudo git clone https://github.com/attenzione/android-ColorPickerPreference
sudo git clone https://github.com/aws-samples/aws-java-sample
sudo git clone https://github.com/b0noI/TicTacToe
sudo git clone https://github.com/buddy-works/simple-java-project
sudo git clone https://github.com/bytedeco/sample-projects
sudo git clone https://github.com/cacheflowe/haxademic
sudo git clone https://github.com/callicoder/javafx-examples
sudo git clone https://github.com/cfdobber/maven-java9-jigsaw
sudo git clone https://github.com/citrusframework/citrus-samples
sudo git clone https://github.com/code-not-found/grpc-java
sudo git clone https://github.com/cowtowncoder/java-uuid-generator
sudo git clone https://github.com/devopstrainingblr/Maven-Java-Project
sudo git clone https://github.com/dmpe/JavaFX
sudo git clone https://github.com/eclipse/jetty.project
sudo git clone https://github.com/eclipse/paho.mqtt.java
sudo git clone https://github.com/edmund-wagner/junrar
sudo git clone https://github.com/FacePlusPlus/facepp-java-sdk
sudo git clone https://github.com/frandorado/spring-projects
sudo git clone https://github.com/FutureProcessing/spring-boot-security-example
sudo git clone https://github.com/galatea-associates/fuse-starter-java
sudo git clone https://github.com/getgauge-examples/java-gradle-selenium
sudo git clone https://github.com/googlearchive/tango-examples-java
sudo git clone https://github.com/GustavoRolimSantos/Java
sudo git clone https://github.com/gwhalin/Memcached-Java-Client
sudo git clone https://github.com/hannonhill/Webservices-Java-Sample-Project
sudo git clone https://github.com/heremaps/here-android-sdk-examples
sudo git clone https://github.com/hibernate/hibernate-demos
sudo git clone https://github.com/hope-for/hope-cloud
sudo git clone https://github.com/hprose/hprose-java
sudo git clone https://github.com/Instagram/ig-json-parser
sudo git clone https://github.com/internetarchive/heritrix3
sudo git clone https://github.com/janpetryk/reddit-bot
sudo git clone https://github.com/jasonray/jersey-starterkit
sudo git clone https://github.com/javaparser/javaparser-maven-sample
sudo git clone https://github.com/jesuino/java-ml-projects
sudo git clone https://github.com/joaomlneto/travis-ci-tutorial-java
sudo git clone https://github.com/journaldev/journaldev
sudo git clone https://github.com/k55k32/cms-admin-end
sudo git clone https://github.com/kelemen/netbeans-gradle-project
sudo git clone https://github.com/kevinsawicki/github-maven-example
sudo git clone https://github.com/labmac/java-project
sudo git clone https://github.com/linuxacademy/content-jenkins-java-project
sudo git clone https://github.com/lkuza2/java-speech-api
sudo git clone https://github.com/m-reza-rahman/javaee-javascript
sudo git clone https://github.com/mcourteaux/CraftMania
sudo git clone https://github.com/microsoft/azure-tools-for-java
sudo git clone https://github.com/mplacona/java-junit-template-project
sudo git clone https://github.com/MyCollab/mycollab
sudo git clone https://github.com/nacos-group/nacos-spring-boot-project
sudo git clone https://github.com/nacos-group/nacos-spring-project
sudo git clone https://github.com/nayuki/Project-Euler-solutions
sudo git clone https://github.com/openjdk/jmc
sudo git clone https://github.com/openjdk/loom
sudo git clone https://github.com/openjdk/skara
sudo git clone https://github.com/OpenNTF/JavascriptAggregator
sudo git clone https://github.com/opentracing-contrib/java-spring-cloud
sudo git clone https://github.com/OvercastNetwork/ProjectAres
sudo git clone https://github.com/OWASP/owasp-java-encoder
sudo git clone https://github.com/panterch/ch.panter.projectzero
sudo git clone https://github.com/peterarsentev/games_oop_javafx
sudo git clone https://github.com/phaniprasad009/Ant-JavaProject
sudo git clone https://github.com/pluralsight-projects/Java-BookStore
sudo git clone https://github.com/pluralsight-projects/Java-BookStoreShoppingCart
sudo git clone https://github.com/quickfix-j/quickfixj
sudo git clone https://github.com/Red5/red5-examples
sudo git clone https://github.com/sap-production/XcodeProjectJavaAPI
sudo git clone https://github.com/sarxos/webcam-capture
sudo git clone https://github.com/schildbach/public-transport-enabler
sudo git clone https://github.com/seis665/java-project
sudo git clone https://github.com/sheefee/simple-sso
sudo git clone https://github.com/shouryaj98/Hotel-Management-Project-Java
sudo git clone https://github.com/skeeto/sample-java-project
sudo git clone https://github.com/slgobinath/Java-Helps-Android
sudo git clone https://github.com/slgobinath/Java-Helps-Java
sudo git clone https://github.com/sormuras/bach
sudo git clone https://github.com/soumyadip007/Java-JavaFx-Swing-Projects-Desktop-Application-GUI-Software
sudo git clone https://github.com/spring-guides/gs-gradle
sudo git clone https://github.com/spring-guides/gs-maven
sudo git clone https://github.com/SquareSquash/java
sudo git clone https://github.com/stoicflame/enunciate
sudo git clone https://github.com/StubbornJava/StubbornJava
sudo git clone https://github.com/teamed/qulice
sudo git clone https://github.com/TEAMMATES/teammates
sudo git clone https://github.com/testdouble/java-testing-example
sudo git clone https://github.com/thorntail/thorntail
sudo git clone https://github.com/tomsquest/java-agent-asm-javassist-sample
sudo git clone https://github.com/treehouse-projects/java-debugging-flashy
sudo git clone https://github.com/treehouse-projects/java-unittesting-vendingmachine
sudo git clone https://github.com/TTFHW/jenkins_pipeline_java_maven
sudo git clone https://github.com/udacity/ud282
sudo git clone https://github.com/vogellacompany/codeexamples-javaweb
sudo git clone https://github.com/wantao666/java-project0
sudo git clone https://github.com/web3j/sample-project-gradle
sudo git clone https://github.com/Yalantis/FlipViewPager.Draco
sudo git clone https://github.com/yrojha4ever/JavaStud
sudo git clone https://github.com/yusufshakeel/Java-Image-Processing-Project